### DISCUSSION TITLE
Welcome to card-games Discussions!

### DISCUSSION THREAD

**Discussion by pibion** [phys2331/card-games#1] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by pibion** [comment]
Trying to figure out what the user input should look like?

```
set:
  type: card
      img: img1.png
      alt-text: arrows, all the same size, pointing the same direction
  type: card
      text: "uniform field"
  type: card
      text: "$\vec{E} = \langle a, b, c \rangle, a, b, c \containedin \R$"
```

**Reply by pibion** [reply]
I *think* the below is "official" YAML syntax that has two documents, each of which contains three cards.

```
---
cards:
    - img: img1.png
      alt-text: arrows, all the same size, pointing the same direction
    - text: uniform field
    - text: $\vec{E} = \langle a, b, c \rangle, a, b, c \containedin \R$
---
cards:
    - img: carrot.png
      alt-text: a rounded, stake-like vegetable with a spray of green on top
    - text: Carrot
    - text: Crunchy, orange food
...
```
